import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import getCurrentUser, { ICurrentUser } from "@/actions/getCurrentUser";

export const metadata: Metadata = {
  title: "Semo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser: ICurrentUser | undefined = await getCurrentUser();
  console.log(currentUser);

  return (
    <html>
      <body>
        <NavBar currentUser={currentUser} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
